Fix tsc compilation errors
    $ ./scripts/builder
    src/lib/inbox/inbox.ts:232:38 - error TS2339: Property 'delayBlocks' does not exist on type '[BigNumber, BigNumber, BigNumber, BigNumber]'.

    232       blockNumber - maxTimeVariation.delayBlocks.toNumber()
                                            ~~~~~~~~~~~

    src/lib/inbox/inbox.ts:235:24 - error TS2339: Property 'delaySeconds' does not exist on type '[BigNumber, BigNumber, BigNumber, BigNumber]'.

    235       maxTimeVariation.delaySeconds.toNumber()